name: proba123
description: A new Flutter project.

version: 1.0.0+14

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_repository:
    path: firebase_repository

  #ui
  charts_flutter: ^0.8.0
  font_awesome_flutter: ^8.5.0
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  auto_size_text: ^2.1.0

  #bloc
  equatable: ^0.6.1
  flutter_bloc: ^0.22.0

  #services
  flutter_barcode_scanner: ^0.1.5+1
  flutter_nfc_reader: ^0.0.23
  flutter_launcher_icons: ^0.7.3
  url_launcher: ^5.2.5 #phone calls

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #flutter pub pub run flutter_launcher_icons:main
  image_path: 'assets/img/main.png'
  android: true
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/img/