name: proba123
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  charts_flutter: ^0.8.0
  font_awesome_flutter: ^8.5.0
  intl: ^0.15.8
  path_provider: ^1.3.0

  #bloc
  equatable: ^0.5.1
  flutter_bloc: ^0.21.0

  #services
  flutter_barcode_scanner: ^0.1.5+1
  flutter_nfc_reader: ^0.0.23

  #firebase
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7 #needed for firebase_auth
  firebase_messaging: ^5.1.6

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/img/avatar.jpg
    - assets/img/gradient.png
    - assets/img/sky.jpg
    - assets/img/nfc.png
    - assets/img/qr.png