name: firebase_repository
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7 #needed for firebase_auth
  firebase_messaging: ^5.1.6
  cloud_firestore: ^0.12.9+6
  rxdart: ^0.22.0

  equatable: ^0.6.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
